name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy via SFTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 22
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        onlyNewer: false
        settings: 'sftp:auto-confirm yes'
        localDir: './'
        remoteDir: '/home/volkiby/web/newsite.volki.by/'
        reverse: true
        ignoreFile: '.gitignore'
